name: Build Spigot

on: push

jobs:
  build:
    name: Build Spigot
    runs-on: ubuntu-latest
    steps:
      - name: Use JDK
        uses: actions/setup-java@v1
        with:
          java-version: "8" # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64
      - name: Get Spigot BuildTools
        # https://hub.spigotmc.org/jenkins/job/BuildTools/
        run: wget https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar
      - name: Build Spigot
        run: java -jar BuildTools.jar --rev 1.16.5
      - name: Organize File
        run: |
          echo "FILE_DATE=$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV
          echo "FILE_NAME=$(ls spigot-*.jar)" >> $GITHUB_ENV
      - name: Upload File
        uses: actions/upload-artifact@v2
        with:
          name: ${{env.FILE_DATE}}-${{env.FILE_NAME}}
          path: ./spigot-*.jar
